# Generated by Django 4.1.6 on 2024-06-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age_Mons', models.IntegerField()),
                ('Gender', models.IntegerField(choices=[(1, 'm'), (0, 'f')])),
                ('A1', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('A2', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('A3', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('A4', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('A5', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('A6', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('A7', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('A8', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('A9', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('Ethnicity', models.IntegerField(choices=[(0, 'Hispanic'), (1, 'Latino'), (2, 'Native Indian'), (3, 'Others'), (4, 'Pacifica'), (5, 'White European'), (6, 'Asian'), (7, 'Black'), (8, 'Middle Eastern'), (9, 'Mixed'), (10, 'South Asian')])),
                ('Jaundice', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('ASD_history', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
            ],
        ),
    ]
